name: Auto - Sync Forked Repository
on:
  schedule:
    - cron: '0 12 * * *' # 每天中午12点运行一次
jobs:
  sync:
    runs - once:
      steps:
        - name: Checkout Forked Repository
          uses: actions/checkout@v3
          with:
            fetch - depth: 0 # 获取完整的提交历史
            ref: _worker.js # 假设主要分支是_worker.js
        - name: Setup Git
          run: |
            git config user.name "leesound"
            git config user.email "leemusic@ik.me"
        - name: Add Upstream Repository
          run: |
            git remote add upstream "https://github.com/lu-lingyun/BPB-Worker-Panel.git"
        - name: Fetch Upstream Changes
          run: git fetch upstream
        - name: Merge Upstream Changes
          run: git merge upstream/_worker.js --no-ff --commit-message="Merge upstream changes"
        - name: Push Changes to Forked Repository
          run: git push origin _worker.js
